// <auto-generated />
namespace Sports_Merchandise_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SoccerMerch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SoccerMerch));
        
        string IMigrationMetadata.Id
        {
            get { return "202408110229544_SoccerMerch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
